GET http://localhost:8000/peliculas
###
GET http://localhost:8000/peliculas/33/
###

POST http://localhost:8000/peliculas/
Content-Type: application/json

{
  "ruta_img_peliculas": "11",
  "titulo": "11",
  "descripcion": "11",
  "link": "11",
  "categoria": "11",
  "apto_menores": "11"
}
###
GET http://localhost:8000/peliculas/82/
###
PUT http://localhost:8000/peliculas/82/
Content-Type: application/json

{
  "ruta_img_peliculas": "55",
  "titulo": "55",
  "descripcion": "55",
  "link": "55",
  "categoria": "55",
  "apto_menores": "55"
}
###
PATCH http://localhost:8000/peliculas/82/
Content-Type: application/json

{
  "ruta_img_peliculas": "66"
}
###
DELETE http://localhost:8000/peliculas/82/
